{% set name = "iopath" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # no tag created on github, but release made to pypi
  # url: https://github.com/facebookresearch/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  # Release commit is
  # https://github.com/facebookresearch/iopath/tree/b3ea6da153ab61b3b8687544c0708a4234a8fb58
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3311c16a4d9137223e20f141655759933e1eda24f8bff166af834af3c645ef01

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - dataclasses
    - portalocker
    - python >={{ python_min }}
    - tqdm
    - typing-extensions

test:
  imports:
    - iopath
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/facebookresearch/iopath
  license: MIT
  license_file: LICENSE
  summary: Lightweight I/O abstraction library


extra:
  recipe-maintainers:
    - thewchan
